- src/__tests__/components/__snapshots__/TransactionsTable.test.tsx.snap
- src/components/AddTransactionButton.tsx
- src/components/Tooltip.tsx
- src/components/TransactionsTable.tsx
Helps identify the transaction id so can be edited in the DB.
> Add tooltip with tx_guid in transactions table

- amplify/backend/function/stockerlambda/src/yahoo.js
- amplify/backend/function/stockerlambda/src/yahoo.test.js
Seems v6 is still running so let's go with this for now.
Closes #48.
> Fix yahoo v10 quote summary deprecation

- src/__tests__/components/pages/investments/DividendChart.test.tsx
- src/components/pages/investments/DividendChart.tsx
Well... Good we added tests in previous PR, 🤦
> Fix dividend missing for ticker in same month

- src/__tests__/app/dashboard/accounts/page.test.tsx
- src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
- src/app/dashboard/accounts/page.tsx
- src/components/pages/accounts/NetWorthHistogram.tsx
When selecting a date, the net worth histogram also goes to that range.
Related to #84
> Net worth histogram date selection

- src/__tests__/apis/BookStorage.test.ts
- src/apis/BookStorage.ts
- src/hooks/useDataSource.ts
Allows to import gzipped Gnucash formatted files
> Import compressed files

- amplify/.config/project-config.json
- amplify/backend/backend-config.json
- amplify/backend/function/stockerlambda/stockerlambda-cloudformation-template.json
- amplify/cli.json
I accidentally deleted some roles so using the opportunity to re-create the stack
> Recreate stack

- amplify/backend/function/stockerlambda/src/yahoo.js
- amplify/backend/function/stockerlambda/src/yahoo.test.js
- jest.config.mjs
- package.json
- src/__tests__/components/buttons/TransactionFormButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/TransactionFormButton.test.tsx.snap
- src/__tests__/components/forms/account/AccountForm.test.tsx
- src/__tests__/components/forms/account/__snapshots__/AccountForm.test.tsx.snap
- src/__tests__/components/forms/transaction/MainSplit.test.tsx
- src/__tests__/components/forms/transaction/SplitField.test.tsx
- src/__tests__/components/forms/transaction/SplitsField.test.tsx
- src/__tests__/components/forms/transaction/TransactionForm.test.tsx
- src/__tests__/components/forms/transaction/__snapshots__/MainSplit.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/SplitField.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/SplitsField.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
- src/__tests__/components/pages/accounts/__snapshots__/LatestTransactions.test.tsx.snap
- src/book/entities/Split.ts
- src/book/entities/Transaction.ts
- src/components/buttons/TransactionFormButton.tsx
- src/components/forms/transaction/MainSplit.tsx
- src/components/forms/transaction/SplitField.tsx
- src/components/forms/transaction/SplitsField.tsx
- src/components/forms/transaction/TransactionForm.tsx
- src/components/forms/transaction/types.d.ts
- src/components/pages/account/TransactionsTable.tsx
- src/components/pages/accounts/LatestTransactions.tsx
- src/css/globals.css
- tailwind.config.js
Previous version was a bit clunky and made user repeat some typing and didn't work some edge cases. Current design tries to simplify the amount of fields the user sees together with the typing.
Let's put couple of examples for sumarising logic.
- The user types in the amount which is the quantity field of split number 100
- Given the main currency is the one from split 1, the value of that split is also 100.
- When the user selects the SGD account, we know the currency for this account so we use the **value** of the first split to set it to the **value** of the second split.
- Now that the second split has a value, then within this same split we have all the info we need to calculate quantity (which is how many SGD the account gets) by transforming 100 euros to X SGD, the conversion rate …
> Redesign transaction form

- package.json
- src/__tests__/components/pages/accounts/MonthlyTotalHistogram.test.tsx
- src/components/pages/accounts/MonthlyTotalHistogram.tsx
- yarn.lock
Make sure we show 9 months for monthly total graphs to match it with net worth histogram.
Also remove sharp to see if it fixes images not appearing: https://github.com/aws-amplify/amplify-hosting/issues/3194
> Fix dates for monthly totals

- src/__tests__/components/buttons/TransactionFormButton.test.tsx
- src/components/buttons/TransactionFormButton.tsx
> Fix form update

- src/__tests__/components/buttons/__snapshots__/SaveButton.test.tsx.snap
- src/__tests__/components/onboarding/Onboarding.test.tsx
- src/__tests__/components/onboarding/__snapshots__/CustomTooltip.test.tsx.snap
- src/components/ThemeButton.tsx
- src/components/buttons/SaveButton.tsx
- src/components/onboarding/CustomTooltip.tsx
- src/components/onboarding/Onboarding.tsx
New steps showing the Save and Theme buttons respectively
> Extend onboarding

- src/__tests__/components/DateRangeInput.test.tsx
- src/__tests__/components/forms/account/AccountForm.test.tsx
- src/__tests__/components/forms/currency/CurrencyForm.test.tsx
- src/__tests__/components/forms/currency/__snapshots__/CurrencyForm.test.tsx.snap
- src/__tests__/components/forms/transaction/SplitField.test.tsx
- src/__tests__/components/forms/transaction/__snapshots__/SplitsField.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
- src/__tests__/components/onboarding/Onboarding.test.tsx
- src/__tests__/components/onboarding/__snapshots__/CustomTooltip.test.tsx.snap
- src/book/entities/Transaction.ts
- src/components/DateRangeInput.tsx
- src/components/forms/account/AccountForm.tsx
- src/components/forms/currency/CurrencyForm.tsx
- src/components/forms/transaction/MainSplit.tsx
- src/components/forms/transaction/SplitField.tsx
- src/components/forms/transaction/SplitsField.tsx
- src/components/onboarding/CustomTooltip.tsx
- src/components/onboarding/Onboarding.tsx
Simplify onboarding and fix some bugs after some feedback
> Improve onboarding

- src/__tests__/app/dashboard/settings/commodities/[guid]/page.test.tsx
- src/__tests__/app/dashboard/settings/commodities/__snapshots__/page.test.tsx.snap
- src/__tests__/components/buttons/CommodityFormButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/CommodityFormButton.test.tsx.snap
- src/__tests__/components/forms/commodity/CommodityForm.test.tsx
- src/__tests__/components/forms/commodity/__snapshots__/CommodityForm.test.tsx.snap
- src/__tests__/components/selectors/NamespaceSelector.test.tsx
- src/app/dashboard/settings/commodities/page.tsx
- src/book/__tests__/entities/Commodity.test.ts
- src/book/entities/Commodity.ts
- src/components/buttons/CommodityFormButton.tsx
- src/components/forms/commodity/CommodityForm.tsx
- src/components/selectors/AccountTypeSelector.tsx
- src/components/selectors/NamespaceSelector.tsx
- src/components/selectors/index.ts
Adds new button and form for adding new commodities. Commodities can't be deleted nor updated yet.
> Add commodity form

- src/__tests__/app/dashboard/commodities/[guid]/__snapshots__/page.test.tsx.snap
- src/__tests__/app/dashboard/commodities/[guid]/page.test.tsx
- src/__tests__/components/buttons/PriceFormButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/PriceFormButton.test.tsx.snap
- src/__tests__/components/forms/price/PriceForm.test.tsx
- src/__tests__/components/forms/price/__snapshots__/PriceForm.test.tsx.snap
- src/app/dashboard/commodities/[guid]/page.tsx
- src/book/__tests__/entities/Price.test.ts
- src/book/entities/Price.ts
- src/components/buttons/PriceFormButton.tsx
- src/components/forms/account/AccountForm.tsx
- src/components/forms/account/types.d.ts
- src/components/forms/commodity/CommodityForm.tsx
- src/components/forms/price/PriceForm.tsx
- src/components/forms/price/types.d.ts
- src/components/forms/transaction/types.d.ts
With this we can now add and edit prices. If you add a price with the same commodity -> currency and same date, it overrides the existing one.
> Add Price button and form

- src/__tests__/components/forms/price/PriceForm.test.tsx
- src/__tests__/components/pages/commodity/PricesTable.test.tsx
- src/__tests__/components/pages/commodity/__snapshots__/PricesTable.test.tsx.snap
- src/components/forms/price/PriceForm.tsx
- src/components/pages/commodity/PricesTable.tsx
Add buttons to update/delete price instances
> Add price actions

- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/__tests__/components/pages/account/SplitsHistogram.test.tsx
- src/__tests__/components/pages/account/__snapshots__/InvestmentInfo.test.tsx.snap
- src/__tests__/layout/__snapshots__/Footer.test.tsx.snap
- src/app/dashboard/investments/page.tsx
- src/book/models/InvestmentAccount.ts
- src/components/pages/account/InvestmentInfo.tsx
- src/components/pages/investments/InvestmentsTable.tsx
- src/css/globals.css
Adds investment stats (like latest known price, avg price, etc.) for accounts that are investments
> Add investment stats to account page

- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/__tests__/components/pages/account/__snapshots__/InvestmentInfo.test.tsx.snap
- src/components/pages/account/InvestmentInfo.tsx
Crashed for some stocks where we bought in EUR but dividend is distributed in USD. It's an edge case but can find in VHYL.AS for example
> Fix bug with investments with different dividend currency

- src/__tests__/hooks/useDataSource.test.ts
- src/hooks/useDataSource.ts
The specific account keys i.e. `/api/accounts/<guid>` do change when importing a new book because the accounts are different. With the previous version we were setting the keys to undefined but that keeps the key in the cache and may cause issues. With the current change we iterate over the cache and then delete the keys that belong to specific accounts and then we just mutate as undefined
> Fix import book swr keys issue

- amplify.yml
- src/__tests__/app/user/login/page.test.tsx
- src/__tests__/components/buttons/SaveButton.test.tsx
- src/__tests__/hooks/useBookStorage.test.ts
- src/__tests__/lib/getUser.test.ts
- src/app/user/login/page.tsx
- src/components/buttons/SaveButton.tsx
- src/helpers/env.ts
- src/hooks/useBookStorage.ts
- src/hooks/useDataSource.ts
- src/lib/getUser.ts
also renamed demo to staging as we will be using this probably for e2e in the future and other things.
> Pass USER_BRANCH variable to build for demo site

- amplify.yml
- src/__tests__/app/user/login/page.test.tsx
- src/__tests__/components/buttons/SaveButton.test.tsx
- src/__tests__/hooks/useBookStorage.test.ts
- src/__tests__/lib/getUser.test.ts
- src/app/user/login/page.tsx
- src/components/buttons/SaveButton.tsx
- src/helpers/env.ts
- src/hooks/useBookStorage.ts
- src/hooks/useDataSource.ts
- src/lib/getUser.ts
sync-branches: New code has just landed in master, so let's bring staging up to speed!
> sync: master to staging

- amplify/backend/api/stocker/cli-inputs.json
Forgot to add new endpoints from Stocker. Added with:
```
amplify update api
```
> Create new backend endpoints

- src/__tests__/app/dashboard/layout.test.tsx
- src/app/dashboard/layout.tsx
- src/app/layout.tsx
- src/hooks/useSession.tsx
- src/lib/auth0-provider.ts
Seems the Auth0Provider doesn't send to the login page when not authenticated so doing this manually in the dashboard layout
> Redirect to login if not auth

- package.json
- src/__tests__/app/dashboard/layout.test.tsx
- src/__tests__/app/user/layout.test.tsx
- src/__tests__/app/user/login/page.test.tsx
- src/__tests__/components/buttons/SaveButton.test.tsx
- src/__tests__/components/buttons/ThemeButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/ThemeButton.test.tsx.snap
- src/__tests__/components/pages/account/InvestmentChart.test.tsx
- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/__tests__/hooks/api.test.tsx
- src/__tests__/hooks/state/useTheme.test.tsx
- src/__tests__/hooks/useDataSource.test.ts
- src/app/layout.tsx
- src/app/user/layout.tsx
- src/components/buttons/SaveButton.tsx
- src/components/buttons/ThemeButton.tsx
- src/hooks/state/index.ts
- src/hooks/state/useTheme.ts
- src/hooks/useDataSource.ts
- src/layout/RootLayout.tsx
- yarn.lock
Move the last usages of swr (state) to react-query and remove the library completely!
> Remove swr

- src/__tests__/app/dashboard/accounts/page.test.tsx
- src/__tests__/components/DateRangeInput.test.tsx
- src/__tests__/components/pages/accounts/IncomeExpenseHistogram.test.tsx
- src/__tests__/components/pages/accounts/MonthlyTotalHistogram.test.tsx
- src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
- src/__tests__/lib/queries/getMonthlyTotals.test.ts
- src/app/dashboard/accounts/page.tsx
- src/components/DateRangeInput.tsx
- src/components/pages/accounts/IncomeExpenseHistogram.tsx
- src/components/pages/accounts/MonthlyTotalHistogram.tsx
- src/components/pages/accounts/NetWorthHistogram.tsx
- src/hooks/api/useSplits.ts
- src/lib/queries/getAccountsTotals.ts
- src/lib/queries/getMonthlyTotals.ts
There was a misalignment between networth histogram and the absolute totals in the networth pie. This is because the selected date was not being used to convert the quantities when calculating absolute totals.
> Fix accounts total calculation

- src/__tests__/components/pages/account/InvestmentChart.test.tsx
- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/__tests__/components/pages/investments/InvestmentsTable.test.tsx
- src/app/dashboard/investments/page.tsx
- src/book/__tests__/models/InvestmentAccount.test.ts
- src/book/models/InvestmentAccount.ts
- src/components/pages/account/InvestmentChart.tsx
- src/components/pages/account/InvestmentInfo.tsx
- src/components/pages/accounts/NetWorthHistogram.tsx
- src/components/pages/investments/InvestmentsTable.tsx
- src/css/globals.css
Display realized profit for when positions are closed.
> Improve investment info

- src/__tests__/app/dashboard/accounts/[guid]/__snapshots__/page.test.tsx.snap
- src/__tests__/app/dashboard/accounts/[guid]/page.test.tsx
- src/__tests__/app/dashboard/accounts/page.test.tsx
- src/__tests__/components/charts/NetWorthHistogram.test.tsx
- src/__tests__/components/pages/account/AssetInfo.test.tsx
- src/__tests__/components/pages/account/Header.test.tsx
- src/__tests__/components/pages/account/InvestmentChart.test.tsx
- src/__tests__/components/pages/account/__snapshots__/AssetInfo.test.tsx.snap
- src/__tests__/components/pages/account/__snapshots__/Header.test.tsx.snap
- src/app/dashboard/accounts/[guid]/page.tsx
- src/app/dashboard/accounts/page.tsx
- src/book/prices/PriceDBMap.ts
- src/components/charts/NetWorthHistogram.tsx
- src/components/charts/index.ts
- src/components/pages/account/AssetInfo.tsx
- src/components/pages/account/Header.tsx
- src/components/pages/account/InvestmentChart.tsx
- src/components/pages/account/TransactionsTable.tsx
- src/components/pages/account/index.ts
- src/components/pages/accounts/index.ts
- src/hooks/api/useSplits.ts
Start of custom page for Assets. Only adding total and networth histogram for now.
> AssetInfo page

- src/__tests__/components/charts/AssetSankey.test.tsx
- src/__tests__/components/pages/account/AssetInfo.test.tsx
- src/__tests__/components/pages/account/SpendWidget.test.tsx
- src/__tests__/components/pages/account/TotalWidget.test.tsx
- src/__tests__/components/pages/account/__snapshots__/AssetInfo.test.tsx.snap
- src/__tests__/hooks/api/useSplits.test.tsx
- src/components/charts/AssetSankey.tsx
- src/components/pages/account/AssetInfo.tsx
- src/components/pages/account/SpendWidget.tsx
- src/components/pages/account/TotalWidget.tsx
- src/hooks/api/index.ts
- src/hooks/api/useSplits.ts
Add widget in assets info to show monthly total spend and difference from previous month
> Add monthly expense widget

- src/lib/Stocker.ts
Just realized prices for funds are not updated since 8th Jan when I changed the namespace... :/
> Fix fund retrieval

- src/__tests__/components/charts/NetWorthHistogram.test.tsx
- src/__tests__/components/pages/accounts/IncomeExpenseHistogram.test.tsx
- src/book/__tests__/entities/Transaction.test.ts
- src/book/entities/Transaction.ts
- src/components/charts/NetWorthHistogram.tsx
- src/components/forms/account/AccountForm.tsx
- src/components/onboarding/Onboarding.tsx
- src/components/pages/accounts/IncomeExpenseHistogram.tsx
I really need an e2e test for this...
> Fix onboarding

- package.json
- src/__tests__/components/charts/TotalsPie.test.tsx
- src/__tests__/components/pages/account/AssetInfo.test.tsx
- src/__tests__/components/pages/account/IEInfo.test.tsx
- src/__tests__/components/pages/account/__snapshots__/AssetInfo.test.tsx.snap
- src/__tests__/components/widgets/MonthChange.test.tsx
- src/__tests__/components/widgets/__snapshots__/MonthChange.test.tsx.snap
- src/book/Money.ts
- src/book/__tests__/Money.test.ts
- src/components/charts/AssetSankey.tsx
- src/components/charts/ChartJS.tsx
- src/components/charts/TotalsPie.tsx
- src/components/pages/account/AssetInfo.tsx
- src/components/pages/account/IEInfo.tsx
- src/components/pages/account/TotalWidget.tsx
- src/components/widgets/MonthChange.tsx
- src/constants/colors.ts
- src/helpers/accountsTotalAggregations.ts
- src/hooks/api/useSplits.ts
- yarn.lock
> Accounts table for asset accounts

- package.json
- src/__tests__/app/user/login/page.test.tsx
- src/__tests__/components/buttons/SaveButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/SaveButton.test.tsx.snap
- src/__tests__/hooks/api.test.tsx
- src/__tests__/hooks/api/useInvestments.test.tsx
- src/__tests__/hooks/api/useMainCurrency.test.ts
- src/__tests__/hooks/api/usePrices.test.ts
- src/__tests__/hooks/state/useOnline.test.tsx
- src/app/dashboard/layout.tsx
- src/app/user/layout.tsx
- src/app/user/login/page.tsx
- src/components/buttons/SaveButton.tsx
- src/components/tables/TransactionsTable.tsx
- src/hooks/api/index.ts
- src/hooks/api/useAccounts.ts
- src/hooks/api/useCommodities.ts
- src/hooks/api/useInvestments.ts
- src/hooks/api/useMainCurrency.ts
- src/hooks/api/usePrices.ts
- src/hooks/api/useSplits.ts
- src/hooks/state/index.ts
- src/hooks/state/useOnline.ts
- src/hooks/state/useTheme.tsx
- src/layout/RootLayout.tsx
- yarn.lock
Save button now is disabled and red if there is no internet connection
As an extra, added networkMode: 'always' to all react-queries. I tried it as a default but seems there's a bug where if onLine navigator status changes, then queries are left in paused state...
> Add offline detection

- src/__tests__/components/ProfileDropdown.test.tsx
- src/__tests__/components/__snapshots__/ProfileDropdown.test.tsx.snap
- src/__tests__/components/buttons/ExportButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/ExportButton.test.tsx.snap
- src/components/ProfileDropdown.tsx
- src/components/buttons/ExportButton.tsx
- src/setupTests.ts
Let users export the file from the app directly. It's the same as copying the file from google drive but it's useful to have it built in
> Add export functionality

- src/__tests__/hooks/api/useCashFlow.test.tsx
- src/components/charts/AssetSankey.tsx
- src/hooks/api/useCashFlow.ts
Well, the SQL became more complicated but it covers the use cases
> Fix multiple split

- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/book/__tests__/models/InvestmentAccount.test.ts
- src/book/models/InvestmentAccount.ts
- src/book/types/index.d.ts
- src/components/pages/account/InvestmentInfo.tsx
Set the price in the investment account to be on the date we are processing the splits. This is so we show the right value at the selected date.
> Set price on processing splits

- src/__tests__/components/pages/account/InvestmentChart.test.tsx
- src/__tests__/components/pages/account/InvestmentInfo.test.tsx
- src/__tests__/components/pages/account/__snapshots__/InvestmentInfo.test.tsx.snap
- src/book/__tests__/entities/Account.test.ts
- src/book/__tests__/models/InvestmentAccount.test.ts
- src/book/entities/Account.ts
- src/book/models/InvestmentAccount.ts
- src/components/pages/account/InvestmentChart.tsx
- src/components/pages/account/InvestmentInfo.tsx
Some changes to support robo advisor investments:
- Robo advisor investments are accounts categorised as "INVESTMENT"
- They use a currency (before it was not possible)
> Support for roboadvisors

- src/__tests__/app/dashboard/accounts/[guid]/page.test.tsx
- src/__tests__/app/dashboard/commodities/[guid]/__snapshots__/page.test.tsx.snap
- src/__tests__/app/dashboard/commodities/[guid]/page.test.tsx
- src/__tests__/components/forms/commodity/CommodityForm.test.tsx
- src/app/dashboard/accounts/[guid]/page.tsx
- src/app/dashboard/commodities/[guid]/page.tsx
- src/book/entities/Account.ts
- src/book/entities/Commodity.ts
- src/components/forms/commodity/CommodityForm.tsx
- src/components/pages/account/Header.tsx
Let user delete unused commodities
> Delete unused commodities

- src/app/dashboard/commodities/[guid]/page.tsx
- src/components/forms/account/AccountForm.tsx
- src/components/forms/commodity/CommodityForm.tsx
- src/components/forms/price/PriceForm.tsx
Just in line with the TransactionForm. Improve the types
> Type improvement for forms

- src/__tests__/components/pages/accounts/LatestTransactions.test.tsx
- src/__tests__/components/pages/accounts/__snapshots__/LatestTransactions.test.tsx.snap
- src/components/pages/accounts/LatestTransactions.tsx
> Fix latest txs on split event

- src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
- src/__tests__/lib/queries/getAccountsTotals.test.ts
- src/book/__tests__/entities/Transaction.test.ts
- src/book/entities/Account.ts
- src/book/entities/Commodity.ts
- src/book/entities/Split.ts
- src/book/entities/Transaction.ts
- src/components/forms/transaction/TransactionForm.tsx
Adding transactions in the future works but then you can't see them nor edit them so it's troublesome. Adding validation for that.
> Add max date validation

- src/__tests__/app/dashboard/editor/__snapshots__/page.test.tsx.snap
- src/__tests__/app/dashboard/editor/page.test.tsx
- src/__tests__/components/SQLEXplorer.test.tsx
- src/__tests__/components/SQLEditor.test.tsx
- src/__tests__/components/__snapshots__/SQLEXplorer.test.tsx.snap
- src/__tests__/components/__snapshots__/SQLEditor.test.tsx.snap
- src/__tests__/layout/__snapshots__/LeftSideBar.test.tsx.snap
- src/app/dashboard/editor/layout.tsx
- src/app/dashboard/editor/page.tsx
- src/components/SQLEditor.tsx
- src/components/SQLExplorer.tsx
- src/layout/Menu.tsx
SQL editor to interact with local data.
This is useful for fixing things on site or bulk edit stuff. It's also dangerous but the good thing is that the changes are not saved until you click save so. Note that if a user edits something with SQL without saving and then adds an account/tx it will save that.
This page has loads of potential as it could become something like databricks/etc where you can build graphs directly from the query results. Need to do some research to see if there is some syntax that can be used directly and tie it to chartjs. Another thing to add is autocomplete. Not a priority but it's a decent project to take on with external PRs
Closes #91
> Basic SQL editor

- src/__tests__/hooks/api/useCashFlow.test.tsx
- src/hooks/api/useCashFlow.ts
> Fix multiple split INCOME cash flow

- .github/workflows/backend-ci.yml
- .github/workflows/frontend-ci.yml
so it triggers build for external contributions
> Add pull_request in workflows

- src/__tests__/components/pages/account/InvestmentChart.test.tsx
- src/components/pages/account/InvestmentChart.tsx
> Fixed tooltip label on stock chart

- amplify/backend/function/stockerlambda/package.json
- package.json
- src/__tests__/components/buttons/ImportButton.test.tsx
- src/__tests__/components/buttons/__snapshots__/ImportButton.test.tsx.snap
- src/__tests__/components/buttons/import/DBImportButton.test.tsx
- src/__tests__/components/buttons/import/__snapshots__/DBImportButton.test.tsx.snap
- src/components/buttons/ImportButton.tsx
- src/components/buttons/import/DBImportButton.tsx
- src/css/globals.css
- yarn.lock
Right now you can only import data by importing the whole DB file. This is a first step on adding new methods of importing data (i.e. from direct SQL or others). Just preparing a simple UI where new methods can appear
> Import improvement

- src/__tests__/app/actions/getTodayPrices.test.ts
- src/__tests__/app/actions/plaid.test.ts
- src/__tests__/hooks/useSession.test.ts
- src/__tests__/lib/jwt.test.ts
- src/app/actions/getTodayPrices.ts
- src/app/actions/plaid.ts
- src/hooks/useSession.tsx
- src/lib/jwt.ts
Changing role check on the UI to use idToken instead of accessToken.
reference: https://www.reddit.com/r/nextjs/comments/1d1ljom/role_based_authentication_with_auth0_and_nextjs/
> Use id token for role check

- package.json
- src/__tests__/components/forms/transaction/SplitField.test.tsx
- src/__tests__/components/forms/transaction/TransactionForm.test.tsx
- src/__tests__/components/forms/transaction/__snapshots__/SplitField.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/SplitsField.test.tsx.snap
- src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
- src/components/CommodityCard.tsx
- src/components/forms/transaction/MainSplit.tsx
- src/components/forms/transaction/SplitField.tsx
- yarn.lock
Allow more than 3 decimals in value of split field. 
Fixes #910
> Remove decimal constraint for split
