src/__tests__/app/user/logout/page.test.tsx
src/__tests__/components/TransactionsTable.test.tsx
src/__tests__/components/__snapshots__/TransactionsTable.test.tsx.snap
src/__tests__/layout/LeftSideBar.test.tsx
src/__tests__/layout/__snapshots__/LeftSideBar.test.tsx.snap
src/app/dashboard/accounts/[guid]/page.tsx
src/components/TransactionsTable.tsx
src/layout/Menu.tsx

Apparently react-table re-ordering was messing with the order of the items which came already ordered from typeorm query. What I've done is to disable the sorting from the table component and just rely on the ordering that comes from typeorm. Note that this means we can't order by date in the table anymore
Fixes #5

Fix split order in transactions table

---

jest.config.mjs
src/__tests__/app/dashboard/accounts/[guid]/page.test.tsx
src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/app/dashboard/layout.test.tsx
src/__tests__/components/buttons/ImportButton.test.tsx
src/__tests__/components/buttons/SaveButton.test.tsx
src/__tests__/components/buttons/__snapshots__/ImportButton.test.tsx.snap
src/__tests__/components/buttons/__snapshots__/SaveButton.test.tsx.snap
src/__tests__/hooks/useBookStorage.test.ts
src/__tests__/hooks/useDataSource.test.ts
src/app/dashboard/accounts/[guid]/page.tsx
src/app/dashboard/accounts/page.tsx
src/app/dashboard/layout.tsx
src/components/AccountsTable.tsx
src/components/buttons/ImportButton.tsx
src/components/buttons/SaveButton.tsx
src/hooks/index.ts
src/hooks/useBookStorage.ts
src/hooks/useDataSource.ts

This PR adds some UI changes so users see when saving is happening. 
Not only this but I've implemented some state management to know when saving is happening as now it can happen from different points in the code. (i.e. adding a new account, importing a new book, etc). The state management is implemented using SWR. I know it may feel a bit hacky but I've tried the following approaches without success:
- Using custom hooks doesnt work because the result if the hook is local to the component rendering it. This means the state change only happens when you push the Save button but when doing it in other UI components, the SaveButton component doesn't realize about that.
- Moving the datasource to a context. This one worked but the problem is that the datasource is used in multiple parts of …

Saving indicator and save after modification

---

src/__tests__/components/forms/transaction/__snapshots__/SplitField.test.tsx.snap
src/__tests__/components/forms/transaction/__snapshots__/SplitsField.test.tsx.snap
src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
src/book/__tests__/entities/Transaction.test.ts
src/book/entities/Transaction.ts
src/components/forms/transaction/SplitField.tsx

Fixes #101 
As an extra, it also fixes another bug where we would call `getExchangeRate` for values of 0 which would trigger errors and disallow us to add dividend splits

Fix splits balance validator

---

src/__tests__/components/buttons/TransactionFormButton.test.tsx
src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/book/__tests__/models/InvestmentAccount.test.ts
src/book/models/InvestmentAccount.ts
src/components/buttons/TransactionFormButton.tsx
src/components/forms/transaction/TransactionForm.tsx

In a change we introduced in https://github.com/maffin-io/maffin-app/commit/dca62c03ab2f67abd681772219b1a9f0a81a4f07#diff-28a1eddf39fdf2988e181547dae13df9391fab5a9623fa0df533fc11ef8ea214R75 we changed the way the transaction's currency is selected. Now, if one of the accounts has mainCurrency as currency, that's the transaction's currency. This created some issues with the previous code we had for storing dividends and this solves it.

Support for dividends in different currencies

---

src/__tests__/apis/Stocker.test.ts
src/__tests__/app/dashboard/accounts/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/components/DateRangeInput.test.tsx
src/__tests__/components/TransactionsTable.test.tsx
src/__tests__/components/charts/Chart.test.tsx
src/__tests__/components/pages/account/SplitsHistogram.test.tsx
src/__tests__/components/pages/account/TotalLineChart.test.tsx
src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
src/__tests__/components/pages/accounts/NetWorthPie.test.tsx
src/__tests__/components/pages/investments/DividendChart.test.tsx
src/__tests__/components/pages/investments/WeightsChart.test.tsx
src/app/dashboard/accounts/page.tsx
src/book/__tests__/entities/Account.test.ts
src/book/entities/Account.ts
src/components/charts/Chart.tsx
src/components/pages/account/SplitsHistogram.tsx
src/components/pages/account/TotalLineChart.tsx
src/components/pages/accounts/NetWorthHistogram.tsx
src/components/pages/accounts/NetWorthPie.tsx
src/components/pages/investments/DividendChart.tsx
src/components/pages/investments/WeightsChart.tsx
src/setupTests.ts
src/types/accounts.d.ts

The PR adds a net worth histogram calculated from monthly income - expenses, accumulating net profit. 
The calculation uses a different approach from the piechart net worth which uses assets - liabilities. With my numbers, I'm getting a difference of 3k and I don't know why, maybe I'm missing something or maybe some accounting is done wrong somewhere... will investigate with simpler books to see if this is repeated.
Relates to #84

Add net worth histogram

---

src/__tests__/app/dashboard/accounts/[guid]/page.test.tsx
src/__tests__/app/dashboard/accounts/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/app/dashboard/investments/page.test.tsx
src/__tests__/components/pages/accounts/MonthlyHistogram.test.tsx
src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
src/app/dashboard/accounts/[guid]/page.tsx
src/app/dashboard/accounts/page.tsx
src/app/dashboard/investments/page.tsx
src/components/pages/account/index.ts
src/components/pages/accounts/MonthlyTotalHistogram.tsx
src/components/pages/accounts/NetWorthHistogram.tsx
src/components/pages/accounts/index.ts
src/components/pages/investments/index.ts

Adds expenses/income histograms in the home page to see monthly contribution to those types. The histograms have one serie per children account in that type, only first level taken into account. In the future we can allow users to dig deeper into categories (i.e. "Leisure" one may contain children accounts).
The histogram reacts to the date selection too.
Relates to #84

Add expenses/income histograms to home page

---

src/__tests__/app/dashboard/layout.test.tsx
src/__tests__/components/buttons/AddAccountButton.test.tsx
src/__tests__/components/buttons/ImportButton.test.tsx
src/__tests__/components/buttons/SaveButton.test.tsx
src/__tests__/components/buttons/TransactionFormButton.test.tsx
src/app/dashboard/layout.tsx
src/components/buttons/AddAccountButton.tsx
src/components/buttons/ImportButton.tsx
src/components/buttons/SaveButton.tsx
src/components/buttons/TransactionFormButton.tsx
src/hooks/index.ts
src/hooks/useDataSource.ts

Instead of re-processing the `useDataSource` hook on every component that needs it, we now store the datasource in a context in `dashboard/layout.tsx` and then use the context in the components that need it. This avoids multiple re-processing of datasource and storage hooks (which caused network requests, see issue #133).
Fixes #133

Save datasource in context

---

src/__tests__/components/pages/accounts/AccountsTable.test.tsx
src/components/pages/accounts/AccountsTable.tsx

After changes in #140 we are now seeing negative numbers in AccountsTable for INCOME and LIABILITY accounts. This fixes it.

Fix negative amounts in accounts table

---

src/__tests__/lib/queries/getAccounts.test.ts
src/hooks/api/index.ts
src/lib/queries/getAccounts.ts

So for some reason, having inline `Commodity.find` passed to the fetcher directly fails and we need to encapsulate it within an arrow function. Probably some `this` context or something like that as it fails with `Commodity` being `undefined`

Fix commodities

---

src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
src/components/pages/accounts/NetWorthHistogram.tsx

Before this change, the networth histogram was ignoring the first month of the data, skewing the net worth calculations

Fix networth histogram period

---

src/__tests__/components/buttons/TransactionFormButton.test.tsx
src/__tests__/components/pages/account/TransactionsTable.test.tsx
src/components/buttons/TransactionFormButton.tsx
src/components/pages/account/TransactionsTable.tsx
src/lib/queries/getSplits.ts

Edit/Update was broken because the transaction passed to the Form didn't have all the fields that are needed. Now, when the action is `update` or `delete` in the transaction form button, we load the original transaction and pass that as default value

Load original transaction

---

jest.config.mjs
src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/__tests__/helpers/number.test.ts
src/book/Money.ts
src/book/__tests__/Money.test.ts
src/components/forms/transaction/TransactionForm.tsx
src/helpers/number.ts

With previous implementation, when you removed a split from an already existing transaction, that split was left dangling with still the original account associated but without a transaction which caused errors (when loading splits for that specific account for example).
This PR fixes that by deleting all splits with null transaction after an update. I considered an alternative implementation which was to delete the specific Split in SplitsField component, when the user clicks X but this means that the split is deleted before the user clicks "Update". If they don't update, the split is removed regardless which is bad.

Fix transaction form split update

---

jest.config.mjs
src/__tests__/app/dashboard/accounts/[guid]/page.test.tsx
src/app/dashboard/accounts/[guid]/page.tsx
src/css/globals.css

When doing a run of adding expenses, you usually start from the oldest untracked and keep following chronologically. Currently, the date is auto populated to "now" but it's annoying to change that every time. This change makes that the latest transaction's in the account is populated in the form instead.
Closes #288

Set latest split date when adding tx

---

jest.config.mjs
src/__tests__/app/dashboard/accounts/[guid]/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/layout.test.tsx
src/__tests__/app/user/layout.test.tsx
src/__tests__/components/ThemeButton.test.tsx
src/__tests__/components/equities/__snapshots__/StatisticsWidget.test.tsx.snap
src/__tests__/layout/__snapshots__/Topbar.test.tsx.snap
src/app/dashboard/layout.tsx
src/app/layout.tsx
src/app/user/layout.tsx
src/components/StatisticsWidget.tsx
src/components/ThemeButton.tsx
src/components/pages/accounts/NetWorthPie.tsx
src/css/globals.css
src/hooks/state/index.ts
src/layout/Topbar.tsx

Not perfect yet as we should be loading the theme in the head of the HTML but having some issues with that: https://github.com/vercel/next.js/issues/49830

Load theme early

---

src/__tests__/components/pages/account/__snapshots__/TransactionsTable.test.tsx.snap
src/components/pages/account/TransactionsTable.tsx

Because account being passed to transactions table column was `undefined`, we were rendering the wrong currency for accounts with non `EUR` currency

Fix wrong currency detail page

---

src/__tests__/components/forms/account/AccountForm.test.tsx
src/components/forms/account/AccountForm.tsx

I reordered the mutate calls and this made the monthly balance to update with a big delay. Re-ordering like this so it is instant.

Fix instant refresh for onboarding opening balance

---

src/__tests__/components/buttons/TransactionFormButton.test.tsx
src/app/dashboard/accounts/[guid]/page.tsx
src/components/buttons/TransactionFormButton.tsx

This was a nasty bug. So `TransactionFormButton` was being rendered with some defaultValues and then when re-rendered with new default values, they were not being applied because `React.useState` only applies the values on the first render. Changed the code so the passed default values are always used and applied

Fix transactions table action buttons

---

src/__tests__/lib/queries/getLatestTxs.test.ts
src/lib/queries/getLatestTxs.ts
src/lib/queries/getSplits.ts

Sort by enter date before quantity as per user request

Take enter date into account when sorting splits

---

src/components/pages/account/TransactionsTable.tsx

With previous code it was always showing the same split in the transaction form regardless from which account you were checking the transaction. This made it impossible to update the related accounts (splits). With the current change, we make sure we show the split belonging to the other accounts.

Order split shown when editing transactions

---

amplify/backend/function/stockerlambda/ts/__tests__/yahoo.test.ts
amplify/backend/function/stockerlambda/ts/yahoo.ts

Sometimes yahoo finance returns 0 for close price and that breaks percentage change calculations. With this fix, whenever we find a 0 close price, we set it to the same current price.

Fix no close price stocker

---

src/__tests__/components/forms/account/AccountForm.test.tsx
src/__tests__/components/forms/commodity/CommodityForm.test.tsx
src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/components/forms/account/AccountForm.tsx
src/components/forms/commodity/CommodityForm.tsx
src/components/forms/transaction/TransactionForm.tsx

When we added individual keys for some of the object instances we created new `swr` keys but we forgot to update the code in the forms so it refreshes the key in SWR so the page/component reloads with the updated data.

Fix form updates

---

src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/__tests__/hooks/api.test.tsx
src/book/__tests__/models/InvestmentAccount.test.ts
src/book/models/InvestmentAccount.ts
src/components/forms/transaction/MainSplit.tsx

After https://github.com/maffin-io/maffin-app/pull/515 we changed the tx currency for non currency related transactions to be the linked currency to that commodity. This meant that we can add txs in currency different than the main currency and that's something we didn't allow. This PR fixes the code in order to allow for those type of transactions.

Support dividend txs not in main currency

---

src/__tests__/lib/Stocker.test.ts
src/lib/Stocker.ts

```
Access to XMLHttpRequest at '' from origin 'https://app.maffin.io' has been blocked by CORS policy: Request header field x-requested-with is not allowed by Access-Control-Allow-Headers in preflight response.
```
The header was added in https://github.com/maffin-io/maffin-app/pull/581. It's related to security but removing for now to fix the issue as web is not accessible

Remove x-requested-with header

---

src/__tests__/app/dashboard/accounts/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/components/pages/accounts/IncomeExpenseHistogram.test.tsx
src/__tests__/components/pages/accounts/MonthlyTotalHistogram.test.tsx
src/app/dashboard/accounts/page.tsx
src/components/pages/accounts/IncomeExpenseHistogram.tsx
src/components/pages/accounts/MonthlyTotalHistogram.tsx
src/components/pages/accounts/index.ts
src/lib/queries/getMonthlyTotals.ts

In the previous version, the net worth histogram was calculating net worth from accumulating monthly Income - Expense but this is wrong because Investment assets can increase/decrease value without having expense/income transactions and same when you have different currencies.
I've changed the home page to now have a monthly savings graph and another that shows net worth calculated from deducting liabilities from assets:
There's one thing to be fixed and it's that in calculating net worth, we always pick the latest value of an investment regardless of when the transaction happened. We should make sure we use the correct price for the specific month. Will be fixing next

Fix net worth histogram

---

src/__tests__/components/forms/price/PriceForm.test.tsx
src/__tests__/components/onboarding/Onboarding.test.tsx
src/__tests__/components/pages/accounts/AccountsTable.test.tsx
src/__tests__/components/pages/accounts/IncomeExpenseHistogram.test.tsx
src/__tests__/components/pages/accounts/NetWorthHistogram.test.tsx
src/__tests__/components/pages/accounts/NetWorthPie.test.tsx
src/__tests__/components/pages/accounts/__snapshots__/LatestTransactions.test.tsx.snap
src/__tests__/components/selectors/CommoditySelector.test.tsx
src/__tests__/lib/queries/getMonthlyTotals.test.tsx
src/components/forms/price/PriceForm.tsx
src/components/onboarding/Onboarding.tsx
src/components/pages/accounts/AccountsTable.tsx
src/components/pages/accounts/IncomeExpenseHistogram.tsx
src/components/pages/accounts/LatestTransactions.tsx
src/components/pages/accounts/NetWorthHistogram.tsx
src/components/pages/accounts/NetWorthPie.tsx
src/components/selectors/CommoditySelector.tsx
src/lib/createEquityAccount.ts
src/lib/queries/getMonthlyTotals.ts

The whole net worth and monthly totals was calculated the wrong way. We took a pragmatic approach of taking the latest exchange rates which would show the latest net worth (for current month) the right way. However, this means that for previous month, the net worth was wrong because the exchange rate of other commodities is probably different.
Current changes fix this by changing how we calculate monthlyTotals:
- For assets/liabilities, each month we aggregate the value of all previous months and then convert it using **that month exchange rate**
- For income/expense, we still use the same approach. Each month **only contains the same month totals** and we convert using that month exchange rate.
This is so we can answer this two questions:
- How much did I have in my different currency …

Fix monthly total calculations

---

src/__tests__/app/dashboard/commodities/[guid]/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/commodities/[guid]/page.test.tsx
src/__tests__/components/forms/price/PriceForm.test.tsx
src/__tests__/components/forms/transaction/MainSplit.test.tsx
src/__tests__/components/forms/transaction/SplitField.test.tsx
src/__tests__/components/forms/transaction/SplitsField.test.tsx
src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/__tests__/components/pages/account/InvestmentChart.test.tsx
src/__tests__/components/pages/account/InvestmentInfo.test.tsx
src/__tests__/hooks/api.test.tsx
src/app/dashboard/commodities/[guid]/page.tsx
src/book/__tests__/entities/Price.test.ts
src/book/entities/Price.ts
src/components/forms/price/PriceForm.tsx
src/hooks/api/index.ts

Started trying to optimise the `usePrices` query by modifying the cached data but then realizing it's a bit more complicated due to using `upserts` for inserting new prices which means we have to check via `guid` but also via the conflict keys when upserting. For now taking the strategy of invalidating the keys.

Move usePrices to query

---

package.json
src/book/__tests__/models/InvestmentAccount.test.ts
src/book/models/InvestmentAccount.ts
yarn.lock

We changed the ordering of the splits and didn't reflect as expected in `InvestmentAccount` which caused errors for stocks that had Sell operations. This fixes it.

Fix investment splits ordering

---

amplify/backend/function/stockerlambda/package.json
package.json
src/__tests__/components/forms/account/AccountForm.test.tsx
src/__tests__/components/pages/account/InvestmentInfo.test.tsx
src/__tests__/components/pages/account/__snapshots__/InvestmentInfo.test.tsx.snap
src/__tests__/components/selectors/AccountSelector.test.tsx
src/__tests__/hooks/api/useMainCurrency.test.ts
src/__tests__/hooks/state/useTheme.test.tsx
src/app/dashboard/layout.tsx
src/book/models/InvestmentAccount.ts
src/components/forms/account/AccountForm.tsx
src/components/pages/account/InvestmentInfo.tsx
src/components/pages/account/TransactionsTable.tsx
src/components/pages/accounts/AccountsTable.tsx
src/components/pages/accounts/LatestTransactions.tsx
src/components/pages/investments/InvestmentsTable.tsx
src/components/selectors/AccountSelector.tsx
src/components/selectors/Selector.tsx
src/css/globals.css
src/helpers/classNames.ts
src/hooks/api/useMainCurrency.ts
src/hooks/state/useTheme.ts
yarn.lock

Some minor changes including:
- Fix bug where startDate for investment charts is wrongly calculated (due to `reverse` mutation of splits)
- Change account selector to display color code according to account type
- Sort accounts in account selector
- Show focused/active element in account selector (some css priority issue was avoiding that so even though you could select with arrows, you didn't have any visual feedback).
- Now main currency is selected by default in AccountForm when no default `fk_commodity` is passed.
- mainCurrency and theme keys have now an Infinity gcTime as they never change (unless user acts on it which we manually change then in the case of theme)
- Remove Root account from account selector. We want users creating accounts within the standard Assets/L/I/E accounts

Minor updates

---

src/__tests__/components/forms/account/AccountForm.test.tsx
src/__tests__/components/forms/account/__snapshots__/AccountForm.test.tsx.snap
src/book/__tests__/entities/Account.test.ts
src/book/entities/Account.ts
src/components/forms/account/AccountForm.tsx
src/layout/RootLayout.tsx

Sooo this PR can be a bit controversial, I'm removing the feature of being able to have income/expense accounts in a commodity different than mainCurrency. Some reasoning here:
- When you check income/expense reports you want to see them in your main currency.
- With the current feature, it creates a bit of duality where some accounts that already existed are in EUR but some new accounts I created in SGD after I moved there. However, it's weird to have one of each and for consistency, I prefer all of them to be in EUR.
There is one use case where I think this would make sense and would be when you permanently move to another country. For this case (although not implemented yet) the recommendation anyway is to close and open a new book.

Income/Expense account mainCurrency only

---

src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/components/pages/accounts/AccountsTable.test.tsx
src/__tests__/components/pages/accounts/IncomeExpenseHistogram.test.tsx
src/__tests__/components/pages/accounts/MonthlyTotalHistogram.test.tsx
src/__tests__/components/pages/accounts/NetWorthPie.test.tsx
src/__tests__/hooks/api/useSplits.test.tsx
src/__tests__/lib/queries/getAccountsTotals.test.ts
src/__tests__/lib/queries/getMonthlyTotals.test.ts
src/app/dashboard/accounts/page.tsx
src/book/__tests__/entities/Transaction.test.ts
src/book/__tests__/models/InvestmentAccount.test.ts
src/book/entities/Transaction.ts
src/components/pages/accounts/IncomeExpenseHistogram.tsx
src/components/pages/accounts/MonthlyTotalHistogram.tsx
src/hooks/api/index.ts
src/hooks/api/useSplits.ts
src/lib/queries/getAccountsTotals.ts
src/lib/queries/getMonthlyTotals.ts
src/setupTests.ts
src/types/book.d.ts

Move to a more granular/paginated approach for calculating totals for accounts (either absolute total or monthly aggregation).
This covers most of the home aggregations except the networth histogram which is a bit more complicating and will be doing in subsequent PRs. So far I've been mixing concepts a bit. When saying monthly aggregation it's actually two different things:
- For Income/Expense account it's usually a histogram that shows monthly splits
- For Assets though, what we want to show is the net worth on that specific month and its progression. We don't have many cases to show monthly splits for an Asset account except for maybe in the account detail page

Refactor monthly aggregations

---

src/__tests__/components/pages/accounts/AccountsTable.test.tsx
src/__tests__/components/pages/accounts/NetWorthPie.test.tsx
src/__tests__/helpers/aggregateChildrenTotals.test.ts
src/__tests__/lib/queries/getAccountsTotals.test.ts
src/components/pages/accounts/AccountsTable.tsx
src/components/pages/accounts/NetWorthPie.tsx
src/helpers/aggregateChildrenTotals.ts
src/hooks/api/useSplits.ts
src/lib/queries/getAccountsTotals.ts

First step for refactoring monthly worth. I've extracted the aggregation of children totals into the parent as we will use this on demand. The idea is as follows:
- useAccountsTotal will now return the total for each account without taking into account the children.
- it accepts a select parameter for when you want to add the aggregation so you display accordingly.
It's true that it is extra computing but let's see how it reacts and we can always adapt.

Extract aggregate children totals

---

src/__tests__/components/DateRangeInput.test.tsx
src/__tests__/helpers/monthlyDates.test.ts
src/components/DateRangeInput.tsx
src/components/pages/account/InvestmentChart.tsx
src/components/pages/accounts/IncomeExpenseHistogram.tsx
src/components/pages/accounts/MonthlyTotalHistogram.tsx
src/components/pages/accounts/NetWorthHistogram.tsx
src/helpers/monthlyDates.ts
src/hooks/api/useSplits.ts
src/lib/queries/getMonthlyTotals.ts

When selecting the first of the month in the date picker, we were showing only 6 bars instead of 7 which as a side effect, caused exceptions/errors when changing back to another day with 7 bars because of the keepExistingData of react-query.
This is because when selecting a date in the datepicker, it was selecting the very first second of the day which meant the `splitBy` function of Interval would return less intervals than expected.
For example, if we have `2023-01-01/2023-03-01` what we wanted is three intervals but it would return only 2. To fix that, I've changed the date picker behavior to select the end of the day the user selects so we get one more interval.

Show always 7 bars in histogram

---

src/__tests__/components/pages/account/AccountInfo.test.tsx
src/__tests__/lib/queries/getPrices.test.ts
src/book/__tests__/entities/Price.test.ts
src/book/entities/Price.ts
src/components/pages/account/AccountInfo.tsx
src/hooks/api/usePrices.ts
src/lib/queries/getPrices.ts

Updating cache and price removal were in the wrong order causing the deleted price to still be shown to the user. This PR fixes it.

Fix price deletion

---

src/__tests__/components/forms/transaction/__snapshots__/SplitsField.test.tsx.snap
src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
src/__tests__/components/pages/account/InvestmentChart.test.tsx
src/__tests__/components/pages/investments/InvestmentsTable.test.tsx
src/app/dashboard/accounts/page.tsx
src/book/__tests__/entities/Transaction.test.ts
src/book/entities/Transaction.ts
src/components/forms/transaction/SplitsField.tsx
src/components/forms/transaction/TransactionForm.tsx
src/components/pages/account/InvestmentChart.tsx
src/components/pages/account/InvestmentInfo.tsx
src/components/pages/accounts/index.ts

When creating a new account and wanting to move a bunch of transactions from one to another, it becomes quite difficult as currently you can't edit the main split account and thus, you have to go through the other account in the transaction, filtering for that specific type of transaction (because we don't have global search implemented in the transactions table)

Allow to edit main split account tx form

---

src/__tests__/hooks/useDataSource.test.ts
src/hooks/useDataSource.ts
src/lib/storage/GDriveBookStorage.ts

My compressed file size went from 2.3M to 1.4M when executing this so now we execute every time before saving. It's probably a bit overkill but I don't have a better option right now other than periodically executing which adds a bit of complexity and redundancy so leaving as is for now.

Execute vacuum on save

---

src/__tests__/components/pages/account/InvestmentInfo.test.tsx
src/components/pages/account/InvestmentInfo.tsx

For positions that we've sold and re-bought or sold partially, it's quite annoying to not be able to see the realized profit in detail page

Always show realized profit

---

src/__tests__/components/forms/transaction/SplitField.test.tsx
src/components/forms/transaction/SplitField.tsx
src/components/forms/transaction/SplitsField.tsx

When updating an old transaction, editing anything like the description would change quantities which is very inconvenient. Changed so it only updates rates automatically when adding a new one, not updating.
It may be useful when updating dates but it's not 100% of the cases and it's very annoying to loose the correct quantities when updating so disabling completely.

Do not edit rates when updating

---

src/__tests__/components/pages/account/TransactionsTable.test.tsx
src/book/__tests__/entities/Transaction.test.ts
src/book/entities/Transaction.ts
src/components/pages/account/TransactionsTable.tsx

Make sure we update Splits.CACHE_KEY/accountId for the account we are displaying for cases where user changes the mainsplit account to be a different one.
Currently, without this changes, when changing the split this happens:
This is in the my bank account. The transaction doesn't have a My bank split anymore but stays there because with current code we don't update the key for My bank account.

Fix split update

---

src/__tests__/components/DateRangeInput.test.tsx
src/__tests__/components/charts/AssetSankey.test.tsx
src/__tests__/components/onboarding/Onboarding.test.tsx
src/__tests__/components/pages/account/AssetInfo.test.tsx
src/__tests__/components/pages/account/EarnWidget.test.tsx
src/__tests__/components/pages/account/SpendWidget.test.tsx
src/__tests__/hooks/api/useAccounts.test.tsx
src/__tests__/hooks/api/useCashFlow.test.tsx
src/__tests__/hooks/api/useCommodities.test.tsx
src/__tests__/hooks/api/useMainCurrency.test.tsx
src/__tests__/hooks/api/useSplits.test.tsx
src/__tests__/hooks/state/useInterval.test.tsx
src/__tests__/hooks/state/useTheme.test.tsx
src/components/DateRangeInput.tsx
src/components/charts/AssetSankey.tsx
src/components/pages/account/AssetInfo.tsx
src/components/pages/account/EarnWidget.tsx
src/components/pages/account/SpendWidget.tsx
src/hooks/api/useCashFlow.ts
src/setupTests.ts

Fixed an issue with cash flow calculation where currencies of the accounts were not being take into account. In this version, we now retrieve each split in a transaction related to the account we are generating the cash flow report on and convert the quantities to the currency of the account.
To do that we use the following formula: `(main_split.quantity / main_split.value) * other_split.value`. The beauty of this is that it works for any kind of transaction regardless on the amount of splits it has or the currencies it has.
This is how the "Broker cash" account of the demo account looks like now:
vs before
> 35 was the number of stocks, not the euros amount

Cash flow in currency

---

package.json
src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/components/charts/MonthlyTotalHistogram.test.tsx
src/__tests__/components/pages/account/IEInfo.test.tsx
src/__tests__/helpers/accountsTotalAggregations.test.ts
src/__tests__/hooks/api/useSplits.test.tsx
src/app/dashboard/accounts/page.tsx
src/components/charts/MonthlyTotalHistogram.tsx
src/components/pages/account/IEInfo.tsx
src/helpers/accountsTotalAggregations.ts
src/hooks/api/useSplits.ts
src/layout/RootLayout.tsx
yarn.lock

To prevent UI from flickering when user selects new account/interval/etc it's better to have `keepPreviousData` as default and disable it on specific queries when needed.

Add missing optiong to keep previous query data

---

src/book/Money.ts
src/book/__tests__/Money.test.ts

Discovered a nasty bug when converting Money to a number:
```
money = new Money(9.770491996380624e+27, 'EUR', 24);
expect(money.toNumber(4)).toEqual(9770.4919);
```
this was returning `9770.0004`.
Re-converting the scale as we do with toString and others fixes the problem

Consistent total and monthly net worth

---

src/__tests__/components/charts/TotalsPie.test.tsx
src/__tests__/components/pages/account/TotalWidget.test.tsx
src/__tests__/components/tables/AccountsTable.test.tsx
src/__tests__/hooks/api/useAccountsTotals.test.tsx
src/hooks/api/useAccountsTotals.ts

useAccountsTotals basically merges balance sheet and income statement. The problem though is that, because balance sheet uses prices to aggregate totals in the select, it produced inconsistent results because dataUpdatedAt does not take into account the select results which means useAccountsTotals didn't update the data whenever the select result of useBalanceSheet changed.
To fix that, I've changed `useAccountsTotals` to just aggregate the data always without using useQuery

Fix inconsistent totals

---

src/book/__tests__/entities/Transaction.test.ts
src/book/entities/Transaction.ts

When I refactored the accounts total query to use balance-sheet and income-statement forgot to update the keys so numbers where updated on new transactions

Fix query invalidation for txs

---

src/__tests__/components/buttons/AddTxDropdown.test.tsx
src/__tests__/components/buttons/__snapshots__/AddTxDropdown.test.tsx.snap
src/__tests__/components/pages/account/Header.test.tsx
src/__tests__/components/pages/account/__snapshots__/Header.test.tsx.snap
src/components/buttons/AddTxDropdown.tsx
src/components/pages/account/Header.tsx

Changing the "Add transaction" button to a dropdown. For now it only has "add transaction" as option but I'll be working on adding other actions depending on the account type like:
- dividend
- split
- transfer
and so on. This will help with validation and simplify actions for the users

Transaction add dropdown

---

src/__tests__/components/pages/account/InvestmentInfo.test.tsx
src/__tests__/components/pages/account/InvestmentPlaceholderInfo.test.tsx
src/__tests__/components/tables/AccountsTable.test.tsx
src/__tests__/helpers/accountsTotalAggregations.test.ts
src/__tests__/hooks/api/useAccountsTotals.test.tsx
src/__tests__/hooks/api/useBalanceSheet.test.tsx
src/__tests__/hooks/api/useCashFlow.test.tsx
src/__tests__/hooks/api/useIncomeStatement.test.tsx
src/__tests__/hooks/api/useMonthlyTotals.test.tsx
src/__tests__/hooks/api/useMonthlyWorth.test.tsx
src/__tests__/lib/queries/getAccountsTotals.test.ts
src/__tests__/lib/queries/getMonthlyTotals.test.ts
src/book/Money.ts
src/book/__tests__/Money.test.ts
src/book/__tests__/models/InvestmentAccount.test.ts
src/components/pages/account/InvestmentInfo.tsx

Using total bought is wrong as it counts sold titles too thus showing wrong number.
Also, increased the resolution of `format` call so it uses 4 decimals and then rounds instead of using 2 decimals. This reduces decimal error.

Use cost for total invested

---

README.md
src/__tests__/layout/__snapshots__/LeftSideBar.test.tsx.snap
src/components/onboarding/Onboarding.tsx
src/layout/Menu.tsx

go daddy doesn't support https to https forward so putting http as the original docs url for now.

Fix docs url

---

amplify/backend/function/stockerlambda/ts/app.ts
src/__tests__/app/dashboard/commodities/__snapshots__/page.test.tsx.snap
src/__tests__/app/dashboard/commodities/page.test.tsx
src/__tests__/components/CommodityCard.test.tsx
src/__tests__/components/__snapshots__/CommodityCard.test.tsx.snap
src/__tests__/components/buttons/__snapshots__/SaveButton.test.tsx.snap
src/__tests__/components/forms/commodity/CommodityForm.test.tsx
src/__tests__/components/tooltips/UpgradeTooltip.test.tsx
src/__tests__/components/tooltips/__snapshots__/UpgradeTooltip.test.tsx.snap
src/app/dashboard/commodities/page.tsx
src/book/__tests__/prices/PriceDBMap.test.ts
src/book/prices/PriceDBMap.ts
src/components/CommodityCard.tsx
src/components/buttons/SaveButton.tsx
src/components/forms/commodity/CommodityForm.tsx
src/components/tooltips/UpgradeTooltip.tsx
src/hooks/useDataSource.tsx
src/lib/Stocker.ts

Improve some commodities behaviors:
- Stocker was failing the whole request when 1 of the tickers passed failed which made all commodities to be un-synced. Now, if one of them fails, we just ignore it.
- We display a warning for commodities that don't have any prices
- Whenever a new currency or stock/mutual is added, we re-sync all prices.
There is a new behavior I found that is a bit weird and yet unsolved:
- If you add a new STOCK let's say TSLA which has a base currency of USD but you don't have that currency, it will show the warning. This is solved whenever the user adds USD (and both prices will be synced) but the error message shown to the user is not trivial.

Improve commodities sync

---

src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/__tests__/components/forms/transaction/__snapshots__/TransactionForm.test.tsx.snap
src/__tests__/components/selectors/AccountSelector.test.tsx
src/__tests__/components/tables/TransactionsTable.test.tsx
src/__tests__/hooks/api/useTransactions.test.tsx
src/components/forms/transaction/TransactionForm.tsx
src/components/tables/TransactionsTable.tsx
src/hooks/api/index.ts
src/hooks/api/useTransactions.ts

In previous version the caller of TransactionForm had to know which Transaction entity fields were needed. This is ugly because it moves knowledge out of the component and makes re-usability hard as each time you use the form, you have to repeat the same logic.
Changed it so:
- When action is add, you can still pass default values as needed
- When action is update or delete, you MUST pass a `guid` and not defaultValues. With this guid, the transaction form loads the transaction values needed to show it properly in the form.

Move transaction preloading for transaction form

---

src/__tests__/app/dashboard/accounts/page.test.tsx
src/__tests__/components/charts/AssetSankey.test.tsx
src/__tests__/components/charts/NetWorthHistogram.test.tsx
src/__tests__/components/pages/account/AssetInfo.test.tsx
src/__tests__/components/pages/account/TotalWidget.test.tsx
src/__tests__/components/pages/account/__snapshots__/AssetInfo.test.tsx.snap
src/app/dashboard/accounts/page.tsx
src/components/charts/AssetSankey.tsx
src/components/charts/NetWorthHistogram.tsx
src/components/pages/account/AssetInfo.tsx
src/components/pages/account/TotalWidget.tsx

I've changed the networth histogram to be a bit more configurable so now it can:
- Show assets, liabilities and net worth
- Show only asset account with its own configuration
- Show only liability account with its own configuration
I've decided to not make the values for liabilities absolute as we are talking about debt. Saying that at some point in time the amount is -934 is correct. Would be confusing to say its 934 as the users may think they are in positive.
Fixes #834

Minor improvements to liability page

---

src/__tests__/components/buttons/AddTxDropdown.test.tsx
src/components/buttons/AddTxDropdown.tsx
src/components/forms/transaction/SplitField.tsx

An old bug... passing an instance of a Split object makes the defaultValue reference to be updated when changing the value. Passing now a {} instead of a split instance in the add transaction second split to avoid this and then using `formState.defaultValues` to see if we have set a default for the account type.
Fixes #832

Fix account selection in account form

---

src/__tests__/components/buttons/AddTxDropdown.test.tsx
src/__tests__/components/forms/transaction/SplitField.test.tsx
src/components/buttons/AddTxDropdown.tsx
src/components/forms/transaction/SplitField.tsx

When we added support for RoboAdvisors we made the change that investment accounts can be assigned a currency as commodity. This broke the `txCurrency` selection in the Transaction form as in there we assumed that investment accounts would always have a non currency.
This fixes this by checking in the account of the split is of INVESTMENT type instead of checking the commodity to decide the txCurrency
> We always want the transactions for an investment to be in the currency of the investment itself so the computations done in InvestmentAccount are correct. Otherwise we start mixing currencies and it will throw errors.
Fixes #833

Tx form account selection

---

amplify/backend/function/stockerlambda/ts/__tests__/yahoo.test.ts
amplify/backend/function/stockerlambda/ts/yahoo.ts
src/__tests__/components/tables/PricesTable.test.tsx
src/book/Money.ts
src/book/__tests__/Money.test.ts
src/components/tables/PricesTable.tsx
src/helpers/number.ts

So apparently, for some currency rates, yahoo returns very bad resolution. Take https://finance.yahoo.com/quote/IDREUR=X?.tsrc=fin-srch for example which always returns 0.0001 which is definitely wrong.
The change I've introduced is see if there is some reliable currency in the ticker ('SGD', 'USD' and 'EUR') for now and if there is, use that one as a base
I.E IDREUR=X returns crap but EURIDR=X works as expected. So we apply this behavior too.
This is why in #831 IDR is always 10000. After this change, it shows correct prices:
Also, as an improvement for this, increased the amount of decimals that can be shown in the prices chart and prices table
Fixes #831

Improve yahoo price sync

---

src/__tests__/helpers/number.test.ts
src/book/Money.ts
src/book/__tests__/Money.test.ts
src/components/pages/commodity/PricesChart.tsx
src/helpers/number.ts

Currently, some moneyToString calls are showing too many decimals. This PR fixes that by allowing the user to specify how many decimals they want. This is necessary because when showing exchange rates, we need more than two decimals but for any normal money representation, 2 decimals is fine.

Fix money to string decimals

---

src/__tests__/components/charts/TotalsPie.test.tsx
src/__tests__/components/pages/account/TotalWidget.test.tsx
src/__tests__/components/tables/AccountsTable.test.tsx
src/__tests__/components/tables/__snapshots__/AccountsTable.test.tsx.snap
src/__tests__/lib/queries/getAccountsTotals.test.ts
src/components/charts/TotalsPie.tsx
src/components/pages/account/TotalWidget.tsx
src/components/tables/AccountsTable.tsx
src/lib/queries/getAccountsTotals.ts

Fixes #858 
For the Pie chart, it may be a bit confusing to users as we are displaying positive and negative values in the same dataset. Didn't find a better way to do this for now though so keeping as is:

Fix negative asset values

---

jest.config.mjs
package.json
src/__tests__/app/user/login/page.test.tsx
src/__tests__/hooks/useDataSource.test.ts
src/app/actions/getTodayPrices.ts
src/app/dashboard/commodities/page.tsx
src/hooks/useDataSource.tsx
src/lib/prices.ts
src/lib/yahoo.ts

Sooo I was reading on adding authentication to external apis for nextjs with auth0 and discovered nextjs actions. This is a proposal to move price fetching to nextjs actions which:
- Allows us to remove stocker amplify backend completely which means only one code base, one pipeline, no cors, etc.
- Makes it easier to work with auth0 for api calls (I'm improving this because planning to try integrate with plaid).
Planning to deploy this and see how it behaves. Shouldn't be dangerous as price retrieval is not in the critical path and covered with global try/catch.
PS: If this works, I'll open another PR to remove all extra code and move the tests around

Use nextjs actions for price fetching

---

jest.config.mjs
package.json
src/__tests__/app/actions/getTodayPrices.test.ts
src/__tests__/lib/auth0-provider.test.tsx
src/__tests__/lib/jwt.test.ts
src/__tests__/lib/prices.test.ts
src/app/actions/getTodayPrices.ts
src/app/actions/index.ts
src/layout/RootLayout.tsx
src/lib/auth0-provider.ts
src/lib/auth0-provider.tsx
src/lib/jwt.ts
src/lib/prices.ts
src/setupTests.ts
yarn.lock

Pass access token to actions for better access control and permissions. 
Related to #915 so we can fine grained control.
This involved some changes in auth0 side:
- Create a role called 'premium' for paid users
- Create an api with audience `https://maffin`
- Create an action that includes the roles into the access token as a custom claim
```
const namespace = 'https://maffin';
if (event.authorization) {
api.accessToken.setCustomClaim(`${namespace}/roles`, event.authorization.roles);
}
```
This gives us a way to segment users within the same tenant in Auth0 using roles. This means now we can leave maffin-dev only for development and move all users to the production tenant.

Inject access token to actions

---

.env
.env.staging
src/__tests__/app/actions/getTodayPrices.test.ts
src/__tests__/components/CommodityCard.test.tsx
src/__tests__/components/buttons/SaveButton.test.tsx
src/__tests__/hooks/useBookStorage.test.ts
src/__tests__/hooks/useGapiClient.test.ts
src/__tests__/hooks/useSession.test.ts
src/__tests__/lib/jwt.test.ts
src/__tests__/lib/storage/DemoBookStorage.test.ts
src/app/actions/getTodayPrices.ts
src/components/CommodityCard.tsx
src/components/buttons/SaveButton.tsx
src/helpers/env.ts
src/hooks/useBookStorage.ts
src/hooks/useDataSource.tsx
src/hooks/useGapiClient.ts
src/hooks/useSession.tsx
src/layout/RootLayout.tsx
src/lib/jwt.ts
src/lib/storage/DemoBookStorage.ts

Use `isPremium` flag coming from auth0 jwt token instead of IS_DEMO_PLAN and IS_PLAID_PLAN which depended on the environment being used. This means that we can now have both premium and non premium users in both environments.
This defeats the purpose of having `free.maffin.io` so I'll be deleting the domain and remove the `check_subscription` from app.maffin.io so anyone can login (new users will always be non premium as the role is assigned manually for now).
This behavior is nice because it allows to add extra roles for trying new features. I.e. could have a role called `beta` and then use an `isBeta` flag to enable those features for only those users.

Use roles for premium/standard ui

---

src/__tests__/components/forms/account/AccountForm.test.tsx
src/__tests__/components/forms/transaction/SplitsField.test.tsx
src/__tests__/components/forms/transaction/TransactionForm.test.tsx
src/__tests__/components/onboarding/Onboarding.test.tsx
src/__tests__/hooks/api/useCashFlow.test.tsx
src/__tests__/hooks/api/useSplits.test.tsx
src/__tests__/lib/createEquityAccount.test.ts
src/__tests__/lib/gnucash/migrate.test.ts
src/__tests__/lib/queries/getAccountsTotals.test.ts
src/__tests__/lib/queries/getInvestments.test.ts
src/__tests__/lib/queries/getMainCurrency.test.ts
src/__tests__/lib/queries/getMonthlyTotals.test.ts
src/book/__tests__/entities/Account.test.ts
src/book/__tests__/entities/Book.test.ts
src/book/__tests__/entities/Split.test.ts
src/book/__tests__/entities/Transaction.test.ts
src/book/__tests__/models/InvestmentAccount.test.ts
src/book/entities/Account.ts
src/book/entities/BankConfig.ts
src/book/entities/index.ts
src/book/migrations/1717405195056-AddBankConfig.ts
src/book/migrations/index.ts
src/hooks/useDataSource.tsx

Add new entity for holding online bank configuration. Probably will need to modify in the future as right now the online use case we have is for holding Plaid integration information

Add bank config entity

---

src/__tests__/components/buttons/import/PlaidImportButton.test.tsx
src/__tests__/lib/external/plaid.test.tsx
src/book/__tests__/entities/BankConfig.test.ts
src/book/entities/Account.ts
src/book/entities/BankConfig.ts
src/components/buttons/import/PlaidImportButton.tsx
src/lib/external/plaid.ts

Create bank config entity when the user is linking a new institution. If they try to link again we raise an error.
The bank config contains the accounts that have been linked and the access token

Add plaid duplicate detection

---

src/__tests__/app/layout.test.tsx
src/__tests__/components/__snapshots__/ProfileDropdown.test.tsx.snap
src/__tests__/layout/__snapshots__/Topbar.test.tsx.snap
src/app/layout.tsx
src/components/ProfileDropdown.tsx
src/layout/Topbar.tsx
tailwind.config.ts

Added breakpoints to make the topbar display in mobile "nicely":
This was before:

Responsive Topbar

---

src/__tests__/components/charts/Pie.test.tsx
src/__tests__/components/charts/TotalsPie.test.tsx
src/__tests__/components/pages/account/IEInfo.test.tsx
src/__tests__/components/pages/account/__snapshots__/IEInfo.test.tsx.snap
src/components/charts/Pie.tsx
src/components/charts/TotalsPie.tsx
src/components/pages/account/IEInfo.tsx

- Fix TotalsPie colors. Seems after upgrading passing hardcoded backgroundColors to the dataset doesn't override the autocolors setting.
- Change text for IEInfo widget so it says "Total" for Equity accounts.

Minor fixes from version upgrade

---

src/__tests__/components/pages/account/Header.test.tsx
src/components/pages/account/Header.tsx

Fixes #958.
About the edit note on the issue, I haven´t been able to replicate an account with splits that could be deleted

Fix delete button logic
